name: Bot annunci Subito

on:
  schedule:
    - cron: "*/5 * * * *"  # ogni 5 minuti (UTC)
  workflow_dispatch: {}

concurrency:
  group: subito-bot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run Subito bot (unbuffered)
        env:
          PYTHONUNBUFFERED: "1"
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # opzionale: usa un proxy residenziale se il WAF blocca gli IP GitHub
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          python -u bot_automatico_telegram.py

      - name: Upload diagnostics
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: diagnostica
          path: |
            errore_*.png
            dump_*.html
          if-no-files-found: ignore
