ricerche:
- nome_ricerca: "PSP"
url: "https://www.subito.it/annunci-italia/vendita/usato/?q=psp"
budget_massimo: 50
keyword_da_includere: ["psp"]
keyword_da_escludere: ["solo giochi", "solo gioco", "solo custodia", "riparazione", "cerco"]
file_cronologia: "report_annunci_psp.txt"


- nome_ricerca: "Switch OLED"
url: "https://www.subito.it/annunci-italia/vendita/videogiochi/?q=switch+oled&shp=true"
budget_massimo: 150
keyword_da_includere: ["switch", "oled"]
keyword_da_escludere: ["riparazione", "cerco", "non funzionante"]
file_cronologia: "report_annunci_switch.txt"


- nome_ricerca: "PlayStation 5"
url: "https://www.subito.it/annunci-italia/vendita/videogiochi/?q=ps5&shp=true"
budget_massimo: 200
keyword_da_includere: ["ps5", "playstation 5", "playstation5"]
keyword_da_escludere: ["riparazione", "cerco", "non funzionante", "controller", "solo pad", "cover", "base"]
file_cronologia: "report_annunci_ps5.txt"


- nome_ricerca: "Nintendo 3DS"
url: "https://www.subito.it/annunci-italia/vendita/videogiochi/?q=nintendo+3ds&shp=true"
budget_massimo: 120
keyword_da_includere: ["3ds", "nintendo 3ds"]
keyword_da_escludere: ["solo giochi", "solo gioco", "solo custodia", "riparazione", "cerco", "non funzionante"]
file_cronologia: "report_annunci_3ds.txt"
