# Opzione A (consigliata): accoda i run ogni 5 minuti, NON cancellare quello in corso
name: Bot annunci Subito (queue 5min)


on:
schedule:
- cron: "*/5 * * * *" # ogni 5 minuti (UTC)
workflow_dispatch: {}


concurrency:
group: subito-bot
cancel-in-progress: false # <— accoda invece di cancellare


jobs:
run:
runs-on: ubuntu-latest
timeout-minutes: 20


steps:
- name: Checkout repo
uses: actions/checkout@v4


- name: Setup Python
uses: actions/setup-python@v5
with:
python-version: "3.11"


# Setup Chrome via action (più veloce e stabile di apt-get)
- name: Setup Google Chrome
uses: browser-actions/setup-chrome@v1


- name: Install Python dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt


- name: Run Subito bot
env:
TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
run: |
python bot_automatico_telegram.py


- name: Upload error screenshots
if: ${{ failure() }}
uses: actions/upload-artifact@v4
with:
name: errore-screenshots
path: errore_*.png
if-no-files-found: ignore
