name: Bot Subito

permissions:
  contents: write

on:
  schedule:
    - cron: '*/30 7-20 * * *'  # esempio: ogni 30' in orario diurno
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -U pip
          pip install playwright requests pyyaml
          playwright install --with-deps chromium webkit

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: xvfb-run -a python -u bot_automatico_telegram.py

      - name: Commit & push report updates
        run: |
          set -e
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          BRANCH="${GITHUB_REF_NAME:-${GITHUB_REF#refs/heads/}}"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(bot): update Subito reports $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git pull --rebase --autostash origin "$BRANCH" || true
          git push origin "HEAD:$BRANCH"
