# Nome del nostro flusso di lavoro (workflow)
name: Cerca Annunci Subito

# Eventi che attivano il workflow
on:
  # Permette di avviarlo manualmente dalla pagina Actions di GitHub
  workflow_dispatch:
  
  # Lo avvia automaticamente ogni ora, tutti i giorni
  schedule:
    - cron: '0 * * * *'

# --- MODIFICA CHIAVE: Aggiungiamo i permessi di scrittura ---
permissions:
  contents: write

# Lavori (jobs) da eseguire
jobs:
  # Nome del nostro unico lavoro
  build:
    # Tipo di macchina virtuale su cui eseguire il lavoro
    runs-on: ubuntu-latest

    # Passaggi (steps) da eseguire in sequenza
    steps:
      # 1. Fa il "checkout" del codice dal nostro repository sulla macchina virtuale
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Imposta l'ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installa una versione stabile di Google Chrome
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      # 4. Installa le dipendenze Python, inclusa la libreria "stealth"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 requests selenium-stealth

      # 5. Esegue il nostro script Python
      - name: Run scraper script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot_automatico.py

      # 6. Carica lo screenshot solo se il passo precedente fallisce
      - name: Upload screenshot on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: debug_screenshot.png

      # 7. Salva il file di report aggiornato nel repository
      - name: Commit and push if changed
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add report_annunci_psp.txt
          # Esegue il commit solo se il file è cambiato
          git diff --staged --quiet || git commit -m "Aggiorna cronologia annunci"
          git push
